
--- INDEX---
SELECT * FROM TB_STUDENT;

--테스트 테이블 생성
CREATE TABLE IDX_TEST(
     STUDENT_NO     VARCHAR2(10),
     STUDENT_NAME    VARCHAR2(50)    NOT NULL,
     STUDENT_SSN     VARCHAR2(14),
     STUDENT_ADDRESS VARCHAR2(100)

);



-- 생성된 테이블에 정보 입력
INSERT INTO IDX_TEST(
    SELECT STUDENT_NO,
           STUDENT_NAME,
           STUDENT_SSN,
           STUDENT_ADDRESS
    FROM TB_STUDENT
);

-- 정보 확인
SELECT * FROM IDX_TEST;


 SELECT ROWID,
        STUDENT_NO,
        STUDENT_NAME,
        STUDENT_SSN,
        STUDENT_ADDRESS
    FROM IDX_TEST;

--- 테이블에서 사용하고 있는 인덱스 확인
SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'IDX_TEST';

CREATE UNIQUE INDEX IDX_TEST_UNQ_STUDENT_NO ON IDX_TEST(STUDENT_NO);
        -- 인덱스 이름(이름이기에 짓는건 상관없음) ON 담을 테이블 컬럼명 > 실행하면 인덱스 생성

--CREATE UNIQUE INDEX IDX_TEST_UNQ_STUDENT_NAME ON IDX_TEST(STUDENT_NAME);
-- 위에서 유니크를 썼기 때문에 중복적으로 생성을 못한다. > 에러남
--CREATE INDEX IDX_TEST_UNQ_STUDENT_NAME ON IDX_TEST(STUDENT_NAME);
-- 유니크 빼고 생성

--CREATE INDEX IDX_TEST_UNQ_STUDENT_NAME_SNN ON IDX_TEST(STUDENT_NAME, STUDENT_SNN);
-- 여러개 생성 가능

--계산식 함수 사용 가능
--CREATE INDEX IDX_TEST_UNQ_STUDENT_SNN ON IDX_TEST(SUBSTR(STUDENT_SNN, 1, 6)); 생년월일 기준으로 1부터 6까지


 


